<?php

namespace Database\Seeders;

use App\Models\Soal;
use Illuminate\Database\Seeder;

class SoalSeeder extends Seeder
{
    public function run(): void
    {
        Soal::query()->delete();

        $data = [
            [
                'bab' => 'Bab 1',
                'pertanyaan' => 'Apa tujuan utama berpikir komputasional?',
                'pilihan_a' => 'Menghafal semua istilah komputer',
                'pilihan_b' => 'Menyelesaikan masalah secara runtut dan logis',
                'pilihan_c' => 'Menggunakan komputer tanpa aturan',
                'pilihan_d' => 'Membuat tampilan aplikasi lebih berwarna',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 1',
                'pertanyaan' => 'Memecah masalah besar menjadi bagian kecil disebut proses...',
                'pilihan_a' => 'Dekorasi',
                'pilihan_b' => 'Duplikasi',
                'pilihan_c' => 'Dekomposisi',
                'pilihan_d' => 'Distribusi',
                'jawaban_benar' => 'C',
            ],
            [
                'bab' => 'Bab 1',
                'pertanyaan' => 'Mengapa data perlu diurutkan?',
                'pilihan_a' => 'Agar data lebih sulit dibaca',
                'pilihan_b' => 'Agar data mudah dicari dan dibandingkan',
                'pilihan_c' => 'Agar semua data terhapus',
                'pilihan_d' => 'Agar komputer tidak perlu memproses data',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 1',
                'pertanyaan' => 'Struktur data antrean bekerja dengan prinsip...',
                'pilihan_a' => 'Data terakhir masuk keluar lebih dulu',
                'pilihan_b' => 'Data pertama masuk keluar lebih dulu',
                'pilihan_c' => 'Semua data keluar bersamaan',
                'pilihan_d' => 'Data tidak boleh keluar',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 1',
                'pertanyaan' => 'Contoh kegiatan pencarian data adalah...',
                'pilihan_a' => 'Menyusun buku berdasarkan warna sampul saja',
                'pilihan_b' => 'Mencari nama siswa tertentu dalam daftar kelas',
                'pilihan_c' => 'Menghapus semua catatan',
                'pilihan_d' => 'Mengubah ukuran layar komputer',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 2',
                'pertanyaan' => 'Algoritma adalah...',
                'pilihan_a' => 'Gambar hias pada halaman web',
                'pilihan_b' => 'Urutan langkah untuk menyelesaikan masalah',
                'pilihan_c' => 'Nama perangkat keras komputer',
                'pilihan_d' => 'Kumpulan warna pada desain',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 2',
                'pertanyaan' => 'Pseudocode digunakan untuk...',
                'pilihan_a' => 'Menulis rancangan program dengan bahasa sederhana',
                'pilihan_b' => 'Menghapus seluruh program',
                'pilihan_c' => 'Mempercepat internet',
                'pilihan_d' => 'Mengganti perangkat keras',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 2',
                'pertanyaan' => 'Bagian program yang digunakan untuk menerima data disebut...',
                'pilihan_a' => 'Output',
                'pilihan_b' => 'Input',
                'pilihan_c' => 'Komentar',
                'pilihan_d' => 'Warna',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 2',
                'pertanyaan' => 'Percabangan dalam program digunakan untuk...',
                'pilihan_a' => 'Menentukan aksi berdasarkan kondisi',
                'pilihan_b' => 'Menghapus kode secara otomatis',
                'pilihan_c' => 'Mengubah komputer menjadi printer',
                'pilihan_d' => 'Membuat monitor lebih terang',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 2',
                'pertanyaan' => 'Program yang baik sebaiknya...',
                'pilihan_a' => 'Memiliki langkah yang jelas dan mudah diuji',
                'pilihan_b' => 'Sulit dibaca agar terlihat rumit',
                'pilihan_c' => 'Tidak memiliki alur',
                'pilihan_d' => 'Selalu dibuat tanpa perencanaan',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 3',
                'pertanyaan' => 'Perangkat input berfungsi untuk...',
                'pilihan_a' => 'Menampilkan hasil keluaran',
                'pilihan_b' => 'Memberikan data atau perintah ke komputer',
                'pilihan_c' => 'Menyimpan listrik',
                'pilihan_d' => 'Menghapus sistem operasi',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 3',
                'pertanyaan' => 'Urutan kerja komputer secara umum adalah...',
                'pilihan_a' => 'Output, input, proses',
                'pilihan_b' => 'Input, proses, output',
                'pilihan_c' => 'Proses, output, input',
                'pilihan_d' => 'Input, output, proses',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 3',
                'pertanyaan' => 'Antarmuka komputer berguna untuk...',
                'pilihan_a' => 'Menghubungkan pengguna dengan komputer',
                'pilihan_b' => 'Menghilangkan semua aplikasi',
                'pilihan_c' => 'Memutus jaringan internet',
                'pilihan_d' => 'Mengganti baterai komputer',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 3',
                'pertanyaan' => 'Sistem operasi berperan sebagai...',
                'pilihan_a' => 'Penghubung antara pengguna, aplikasi, dan perangkat keras',
                'pilihan_b' => 'Kabel pengisi daya',
                'pilihan_c' => 'Hiasan pada layar',
                'pilihan_d' => 'Mesin pencari internet',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 3',
                'pertanyaan' => 'Contoh perangkat output adalah...',
                'pilihan_a' => 'Keyboard',
                'pilihan_b' => 'Mouse',
                'pilihan_c' => 'Monitor',
                'pilihan_d' => 'Scanner',
                'jawaban_benar' => 'C',
            ],
            [
                'bab' => 'Bab 4',
                'pertanyaan' => 'Kata kunci dalam pencarian digital digunakan untuk...',
                'pilihan_a' => 'Membantu mesin pencari menemukan informasi yang sesuai',
                'pilihan_b' => 'Menghapus halaman web',
                'pilihan_c' => 'Membuat komputer mati otomatis',
                'pilihan_d' => 'Mengunci semua data',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 4',
                'pertanyaan' => 'Salah satu cara memilih sumber informasi yang baik adalah...',
                'pilihan_a' => 'Hanya melihat judul yang menarik',
                'pilihan_b' => 'Memperhatikan penulis, tanggal, dan lembaga penerbit',
                'pilihan_c' => 'Mengambil informasi dari komentar acak',
                'pilihan_d' => 'Memilih situs yang paling banyak iklannya',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 4',
                'pertanyaan' => 'Pemeriksaan fakta dilakukan untuk...',
                'pilihan_a' => 'Membuat informasi menjadi lebih panjang',
                'pilihan_b' => 'Memastikan informasi tidak keliru atau menyesatkan',
                'pilihan_c' => 'Menghapus sumber informasi',
                'pilihan_d' => 'Mengubah gambar menjadi video',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 4',
                'pertanyaan' => 'Membaca lateral berarti...',
                'pilihan_a' => 'Membaca satu halaman tanpa memeriksa sumber lain',
                'pilihan_b' => 'Menilai informasi dengan membuka sumber lain',
                'pilihan_c' => 'Membaca hanya bagian akhir teks',
                'pilihan_d' => 'Membaca tanpa memahami isi',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 4',
                'pertanyaan' => 'Mengapa informasi digital perlu dibandingkan dengan beberapa sumber?',
                'pilihan_a' => 'Agar kuota internet cepat habis',
                'pilihan_b' => 'Agar kebenarannya lebih dapat dipercaya',
                'pilihan_c' => 'Agar informasi menjadi tidak penting',
                'pilihan_d' => 'Agar hasil pencarian hilang',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 5',
                'pertanyaan' => 'Contoh aplikasi perkantoran adalah...',
                'pilihan_a' => 'Pengolah kata, spreadsheet, dan presentasi',
                'pilihan_b' => 'Kabel, monitor, dan mouse',
                'pilihan_c' => 'Router, modem, dan switch',
                'pilihan_d' => 'Kamera, speaker, dan printer saja',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 5',
                'pertanyaan' => 'Spreadsheet berguna untuk...',
                'pilihan_a' => 'Mengolah data dalam tabel, rumus, dan grafik',
                'pilihan_b' => 'Menghapus file sistem',
                'pilihan_c' => 'Memperbaiki layar pecah',
                'pilihan_d' => 'Mengganti jaringan Wi-Fi',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 5',
                'pertanyaan' => 'Dokumen digital yang baik sebaiknya...',
                'pilihan_a' => 'Tidak memiliki judul dan paragraf',
                'pilihan_b' => 'Disusun rapi agar mudah dibaca',
                'pilihan_c' => 'Berisi teks acak',
                'pilihan_d' => 'Tidak boleh memakai tabel',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 5',
                'pertanyaan' => 'Presentasi digunakan untuk...',
                'pilihan_a' => 'Menyampaikan informasi kepada orang lain',
                'pilihan_b' => 'Menyembunyikan data dari pembaca',
                'pilihan_c' => 'Menghapus aplikasi',
                'pilihan_d' => 'Mengubah komputer menjadi server',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 5',
                'pertanyaan' => 'Integrasi aplikasi perkantoran berarti...',
                'pilihan_a' => 'Menggunakan beberapa aplikasi secara terpadu',
                'pilihan_b' => 'Menghapus semua aplikasi kantor',
                'pilihan_c' => 'Memakai aplikasi tanpa tujuan',
                'pilihan_d' => 'Menyimpan semua dokumen sebagai gambar',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 6',
                'pertanyaan' => 'Jaringan komputer memungkinkan perangkat untuk...',
                'pilihan_a' => 'Saling terhubung dan berbagi data',
                'pilihan_b' => 'Selalu bekerja tanpa listrik',
                'pilihan_c' => 'Tidak dapat berkomunikasi',
                'pilihan_d' => 'Menghapus internet',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 6',
                'pertanyaan' => 'Komunikasi data melibatkan...',
                'pilihan_a' => 'Pengirim, penerima, pesan, dan media transmisi',
                'pilihan_b' => 'Warna, font, dan gambar',
                'pilihan_c' => 'Meja, kursi, dan papan tulis',
                'pilihan_d' => 'Judul, sampul, dan daftar isi',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 6',
                'pertanyaan' => 'Contoh koneksi nirkabel adalah...',
                'pilihan_a' => 'Wi-Fi',
                'pilihan_b' => 'Kabel HDMI',
                'pilihan_c' => 'Kabel listrik',
                'pilihan_d' => 'Kertas cetak',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 6',
                'pertanyaan' => 'Saat berinternet, pengguna sebaiknya...',
                'pilihan_a' => 'Membuka semua tautan tanpa memeriksa',
                'pilihan_b' => 'Berhati-hati terhadap tautan mencurigakan',
                'pilihan_c' => 'Membagikan semua kata sandi',
                'pilihan_d' => 'Mengabaikan keamanan data',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 6',
                'pertanyaan' => 'Internet adalah contoh jaringan yang...',
                'pilihan_a' => 'Menghubungkan banyak jaringan dan perangkat secara luas',
                'pilihan_b' => 'Hanya dapat digunakan oleh satu komputer',
                'pilihan_c' => 'Tidak dapat mengirim data',
                'pilihan_d' => 'Hanya berisi perangkat input',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 7',
                'pertanyaan' => 'Media sosial dapat digunakan untuk...',
                'pilihan_a' => 'Berkomunikasi, berbagi informasi, dan berkolaborasi',
                'pilihan_b' => 'Menghapus semua data sekolah',
                'pilihan_c' => 'Mengganti sistem operasi',
                'pilihan_d' => 'Memperbaiki perangkat keras',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 7',
                'pertanyaan' => 'Etika bermedia sosial berarti...',
                'pilihan_a' => 'Bebas menyakiti orang lain',
                'pilihan_b' => 'Menggunakan media sosial dengan sopan dan bertanggung jawab',
                'pilihan_c' => 'Menyebarkan semua informasi tanpa cek fakta',
                'pilihan_d' => 'Mengabaikan dampak unggahan',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 7',
                'pertanyaan' => 'Konten digital yang baik sebaiknya...',
                'pilihan_a' => 'Memiliki tujuan dan pesan yang jelas',
                'pilihan_b' => 'Meniru semua karya orang lain tanpa izin',
                'pilihan_c' => 'Tidak memperhatikan audiens',
                'pilihan_d' => 'Selalu berisi informasi palsu',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 7',
                'pertanyaan' => 'Hak cipta perlu dihargai karena...',
                'pilihan_a' => 'Karya digital adalah hasil karya seseorang',
                'pilihan_b' => 'Semua karya bebas diambil tanpa aturan',
                'pilihan_c' => 'Agar konten tidak pernah dibuat',
                'pilihan_d' => 'Agar pengguna tidak perlu mencantumkan sumber',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 7',
                'pertanyaan' => 'Jejak digital adalah...',
                'pilihan_a' => 'Rekam aktivitas pengguna di internet',
                'pilihan_b' => 'Bekas sepatu di lantai',
                'pilihan_c' => 'Kabel jaringan yang putus',
                'pilihan_d' => 'Nama perangkat keras komputer',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 8',
                'pertanyaan' => 'Contoh data pribadi adalah...',
                'pilihan_a' => 'Nama, alamat, email, dan kata sandi',
                'pilihan_b' => 'Judul buku umum',
                'pilihan_c' => 'Warna meja kelas',
                'pilihan_d' => 'Nama hari dalam seminggu',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 8',
                'pertanyaan' => 'Kata sandi yang kuat sebaiknya...',
                'pilihan_a' => 'Mudah ditebak dari tanggal lahir',
                'pilihan_b' => 'Tidak mudah ditebak dan tidak memakai data pribadi',
                'pilihan_c' => 'Dibagikan kepada semua orang',
                'pilihan_d' => 'Sama untuk semua akun tanpa perubahan',
                'jawaban_benar' => 'B',
            ],
            [
                'bab' => 'Bab 8',
                'pertanyaan' => 'Autentikasi dua langkah berguna untuk...',
                'pilihan_a' => 'Menambah lapisan keamanan akun',
                'pilihan_b' => 'Menghapus kata sandi',
                'pilihan_c' => 'Membuat akun tanpa perlindungan',
                'pilihan_d' => 'Mematikan perangkat',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 8',
                'pertanyaan' => 'Phishing adalah contoh...',
                'pilihan_a' => 'Kejahatan digital yang mencoba menipu pengguna',
                'pilihan_b' => 'Aplikasi pengolah kata',
                'pilihan_c' => 'Perangkat input',
                'pilihan_d' => 'Teknik membuat presentasi',
                'jawaban_benar' => 'A',
            ],
            [
                'bab' => 'Bab 8',
                'pertanyaan' => 'Cara mencegah penyalahgunaan data pribadi adalah...',
                'pilihan_a' => 'Membagikan kata sandi di media sosial',
                'pilihan_b' => 'Mengatur privasi akun dan tidak membuka tautan mencurigakan',
                'pilihan_c' => 'Menggunakan kata sandi yang sama untuk semua akun',
                'pilihan_d' => 'Memberikan kode verifikasi kepada orang asing',
                'jawaban_benar' => 'B',
            ],
        ];

        foreach ($data as $soal) {
            Soal::create($soal);
        }
    }
}
